/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    vendors: Vendor;
    products: Product;
    rfqs: Rfq;
    quotes: Quote;
    inquiries: Inquiry;
    messages: Message;
    'sample-requests': SampleRequest;
    'product-catalogs': ProductCatalog;
    orders: Order;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    vendors: VendorsSelect<false> | VendorsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    rfqs: RfqsSelect<false> | RfqsSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    'sample-requests': SampleRequestsSelect<false> | SampleRequestsSelect<true>;
    'product-catalogs': ProductCatalogsSelect<false> | ProductCatalogsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  role: 'user' | 'vendor' | 'buyer' | 'admin';
  /**
   * Authentication method used by this user
   */
  oauthProvider?: ('email' | 'google' | 'facebook') | null;
  /**
   * OAuth provider user ID
   */
  oauthId?: string | null;
  /**
   * User avatar URL (from OAuth or uploaded)
   */
  avatar?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Alternative text for accessibility
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * B2B supplier/vendor profiles
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendors".
 */
export interface Vendor {
  id: string;
  /**
   * User account linked to this vendor profile
   */
  user: string | User;
  /**
   * Legal or trading name of the company
   */
  companyName: string;
  /**
   * Type of business entity
   */
  companyType?: ('manufacturer' | 'trading' | 'agent' | 'distributor' | 'other') | null;
  /**
   * Year the company was established
   */
  yearEstablished?: number | null;
  /**
   * Annual revenue range
   */
  annualRevenue?: ('under_1m' | '1m_5m' | '5m_10m' | '10m_50m' | '50m_100m' | 'over_100m') | null;
  /**
   * Number of employees
   */
  employeeCount?: ('1_10' | '11_50' | '51_200' | '201_500' | '501_1000' | 'over_1000') | null;
  /**
   * Primary markets served (e.g., North America, Europe)
   */
  mainMarkets?:
    | {
        market: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Main product categories
   */
  mainProducts?:
    | {
        product: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Location/country of main factory
   */
  factoryLocation?: string | null;
  /**
   * Factory size in square meters
   */
  factorySize?: ('under_1000' | '1000_5000' | '5000_10000' | '10000_50000' | 'over_50000') | null;
  /**
   * Production capacity description (e.g., units per month)
   */
  productionCapacity?: string | null;
  /**
   * Quality certifications (ISO, CE, etc.)
   */
  qualityCertifications?:
    | {
        certification: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Enrolled in trade assurance program
   */
  tradeAssurance?: boolean | null;
  /**
   * Platform-verified supplier
   */
  verifiedSupplier?: boolean | null;
  /**
   * Gold supplier status
   */
  goldSupplier?: boolean | null;
  /**
   * Typical response time for inquiries
   */
  responseTime?: ('24h' | '12h' | '6h' | '2h' | '1h') | null;
  /**
   * Accepts sample orders
   */
  acceptSampleOrders?: boolean | null;
  /**
   * Accepts custom/OEM orders
   */
  acceptCustomOrders?: boolean | null;
  /**
   * Accepted payment terms (e.g., T/T, L/C, PayPal)
   */
  paymentTerms?:
    | {
        term: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Official business registration number
   */
  businessRegistrationNumber?: string | null;
  /**
   * Tax identification number
   */
  taxId?: string | null;
  /**
   * Upload business license document
   */
  businessLicense?: (string | null) | Media;
  /**
   * Company website URL
   */
  companyWebsite?: string | null;
  /**
   * Social media profile links
   */
  socialMediaLinks?:
    | {
        platform: 'linkedin' | 'facebook' | 'twitter' | 'instagram' | 'youtube' | 'other';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * URL to company introduction video (YouTube, Vimeo, etc.)
   */
  companyVideo?: string | null;
  /**
   * Company photos gallery
   */
  companyPhotos?: (string | Media)[] | null;
  /**
   * Key personnel/contact persons
   */
  keyPersonnel?:
    | {
        name: string;
        title?: string | null;
        email?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Company history and background
   */
  companyHistory?: string | null;
  /**
   * Factory photos gallery
   */
  factoryPhotos?: (string | Media)[] | null;
  /**
   * Number of production lines
   */
  productionLinesCount?: number | null;
  /**
   * Quality control process description
   */
  qualityControlProcess?: string | null;
  /**
   * R&D and innovation capabilities
   */
  rndCapability?: string | null;
  /**
   * Warehouse and storage information
   */
  warehouseInformation?: string | null;
  /**
   * Shipping and logistics capabilities
   */
  shippingCapabilities?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * B2B product catalog
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  /**
   * Product name/title
   */
  title: string;
  /**
   * Product description
   */
  description?: string | null;
  /**
   * Vendor/supplier offering this product
   */
  supplier: string | Vendor;
  /**
   * Minimum order quantity
   */
  moq?: number | null;
  /**
   * Bulk pricing tiers (quantity breaks)
   */
  bulkPricingTiers?:
    | {
        minQuantity: number;
        price: number;
        /**
         * Price unit (e.g., USD, EUR)
         */
        unit?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Price per unit
   */
  unitPrice?: number | null;
  /**
   * Samples available for this product
   */
  sampleAvailable?: boolean | null;
  /**
   * Price for sample order
   */
  samplePrice?: number | null;
  /**
   * Custom/OEM orders accepted
   */
  customizationAvailable?: boolean | null;
  /**
   * Production/delivery lead time (e.g., 7-14 days)
   */
  leadTime?: string | null;
  /**
   * Available packaging options
   */
  packagingOptions?:
    | {
        option: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shipping terms (FOB, CIF, etc.)
   */
  shippingTerms?:
    | {
        term: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Accepted payment terms
   */
  paymentTerms?:
    | {
        term: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Product certifications (CE, FDA, etc.)
   */
  productCertifications?:
    | {
        certification: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Harmonized System (HS) tariff code
   */
  hsCode?: string | null;
  /**
   * Country of origin
   */
  originCountry?: string | null;
  /**
   * Product images
   */
  images?: (string | Media)[] | null;
  /**
   * Product category
   */
  category?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Request for Quotations from buyers
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rfqs".
 */
export interface Rfq {
  id: string;
  /**
   * Buyer who created this RFQ
   */
  buyer: string | User;
  /**
   * RFQ title
   */
  title: string;
  /**
   * Detailed RFQ description
   */
  description?: string | null;
  /**
   * Product category
   */
  category?: string | null;
  /**
   * Products requested in this RFQ
   */
  products?:
    | {
        product?: (string | null) | Product;
        quantity?: number | null;
        specifications?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Total quantity needed
   */
  quantity?: number | null;
  /**
   * Target price per unit
   */
  targetPrice?: number | null;
  /**
   * Required delivery date
   */
  deliveryDate?: string | null;
  /**
   * Delivery address/location
   */
  deliveryLocation?: string | null;
  /**
   * Preferred payment terms
   */
  paymentTerms?:
    | {
        term: string;
        id?: string | null;
      }[]
    | null;
  /**
   * RFQ status
   */
  status?: ('draft' | 'open' | 'closed' | 'cancelled') | null;
  /**
   * Quotes submitted for this RFQ
   */
  quotes?: (string | Quote)[] | null;
  /**
   * Selected quote (if any)
   */
  selectedQuote?: (string | null) | Quote;
  /**
   * RFQ expiry date
   */
  expiryDate?: string | null;
  /**
   * Make this RFQ visible to all vendors
   */
  isPublic?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Quotes submitted by suppliers for RFQs
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: string;
  /**
   * RFQ this quote is for
   */
  rfq: string | Rfq;
  /**
   * Vendor/supplier submitting this quote
   */
  supplier: string | Vendor;
  /**
   * Products in this quote
   */
  products?:
    | {
        product?: (string | null) | Product;
        quantity?: number | null;
        unitPrice?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Total quote price
   */
  totalPrice: number;
  /**
   * Price per unit
   */
  unitPrice?: number | null;
  /**
   * Total quantity
   */
  quantity?: number | null;
  /**
   * Production/delivery lead time
   */
  leadTime?: string | null;
  /**
   * Payment terms offered
   */
  paymentTerms?:
    | {
        term: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shipping terms (FOB, CIF, etc.)
   */
  shippingTerms?:
    | {
        term: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Quote validity period (e.g., 30 days)
   */
  validityPeriod?: string | null;
  /**
   * Additional notes or conditions
   */
  notes?: string | null;
  /**
   * Quote status
   */
  status?: ('pending' | 'submitted' | 'accepted' | 'rejected' | 'withdrawn') | null;
  /**
   * Date quote was submitted
   */
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Buyer inquiries to suppliers
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: string;
  /**
   * Buyer making the inquiry
   */
  buyer: string | User;
  /**
   * Vendor/supplier receiving the inquiry
   */
  supplier: string | Vendor;
  /**
   * Product this inquiry is about (if applicable)
   */
  product?: (string | null) | Product;
  /**
   * Inquiry subject
   */
  subject: string;
  /**
   * Inquiry message
   */
  message: string;
  /**
   * Type of inquiry
   */
  inquiryType?: ('product' | 'general' | 'quote') | null;
  /**
   * Inquiry status
   */
  status?: ('new' | 'replied' | 'closed') | null;
  /**
   * File attachments
   */
  attachments?: (string | Media)[] | null;
  /**
   * Last reply date
   */
  lastRepliedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Messages within inquiries
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: string;
  /**
   * Inquiry this message belongs to
   */
  inquiry: string | Inquiry;
  /**
   * User who sent this message
   */
  sender: string | User;
  /**
   * User who receives this message
   */
  receiver: string | User;
  /**
   * Message content
   */
  message: string;
  /**
   * File attachments
   */
  attachments?: (string | Media)[] | null;
  /**
   * Whether message has been read
   */
  read?: boolean | null;
  /**
   * Date message was read
   */
  readAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sample product requests from buyers
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sample-requests".
 */
export interface SampleRequest {
  id: string;
  /**
   * Product sample requested
   */
  product: string | Product;
  /**
   * Buyer requesting the sample
   */
  buyer: string | User;
  /**
   * Vendor/supplier providing the sample
   */
  supplier: string | Vendor;
  /**
   * Number of samples requested
   */
  quantity?: number | null;
  /**
   * Purpose of the sample request
   */
  purpose?: string | null;
  /**
   * Shipping address for sample
   */
  shippingAddress: string;
  /**
   * Sample request status
   */
  status?: ('pending' | 'approved' | 'rejected' | 'shipped' | 'delivered' | 'cancelled') | null;
  /**
   * Price for the sample
   */
  samplePrice?: number | null;
  /**
   * Payment status for sample
   */
  paymentStatus?: ('pending' | 'paid' | 'free') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Product catalogs from suppliers
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-catalogs".
 */
export interface ProductCatalog {
  id: string;
  /**
   * Catalog name
   */
  name: string;
  /**
   * Catalog description
   */
  description?: string | null;
  /**
   * Vendor/supplier who owns this catalog
   */
  supplier: string | Vendor;
  /**
   * Products included in this catalog
   */
  products?: (string | Product)[] | null;
  /**
   * Catalog cover image
   */
  coverImage?: (string | null) | Media;
  /**
   * Catalog category
   */
  category?: string | null;
  /**
   * Make catalog publicly visible
   */
  isPublic?: boolean | null;
  /**
   * URL to download catalog PDF
   */
  downloadUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * B2B orders
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  /**
   * Buyer who placed this order
   */
  buyer: string | User;
  /**
   * Vendor/supplier fulfilling this order
   */
  supplier: string | Vendor;
  /**
   * Type of order
   */
  orderType?: ('standard' | 'sample' | 'custom') | null;
  /**
   * Products in this order
   */
  products?:
    | {
        product: string | Product;
        quantity: number;
        unitPrice: number;
        totalPrice: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Total order amount
   */
  totalAmount: number;
  /**
   * Payment terms
   */
  paymentTerms?:
    | {
        term: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Payment schedule
   */
  paymentSchedule?:
    | {
        amount: number;
        dueDate: string;
        status?: ('pending' | 'paid' | 'overdue') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Deposit amount required
   */
  depositAmount?: number | null;
  /**
   * Whether deposit has been paid
   */
  depositPaid?: boolean | null;
  /**
   * Order protected by trade assurance
   */
  tradeAssurance?: boolean | null;
  /**
   * Amount held in escrow
   */
  escrowAmount?: number | null;
  /**
   * Shipping terms (FOB, CIF, etc.)
   */
  shippingTerms?:
    | {
        term: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Expected delivery date
   */
  deliveryDate?: string | null;
  /**
   * Product inspection date
   */
  inspectionDate?: string | null;
  /**
   * Invoice number
   */
  invoiceNumber?: string | null;
  /**
   * Purchase order number
   */
  poNumber?: string | null;
  /**
   * Order status
   */
  status?:
    | (
        | 'pending'
        | 'confirmed'
        | 'in_production'
        | 'quality_check'
        | 'shipped'
        | 'delivered'
        | 'completed'
        | 'cancelled'
        | 'disputed'
      )
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'vendors';
        value: string | Vendor;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'rfqs';
        value: string | Rfq;
      } | null)
    | ({
        relationTo: 'quotes';
        value: string | Quote;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: string | Inquiry;
      } | null)
    | ({
        relationTo: 'messages';
        value: string | Message;
      } | null)
    | ({
        relationTo: 'sample-requests';
        value: string | SampleRequest;
      } | null)
    | ({
        relationTo: 'product-catalogs';
        value: string | ProductCatalog;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  oauthProvider?: T;
  oauthId?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendors_select".
 */
export interface VendorsSelect<T extends boolean = true> {
  user?: T;
  companyName?: T;
  companyType?: T;
  yearEstablished?: T;
  annualRevenue?: T;
  employeeCount?: T;
  mainMarkets?:
    | T
    | {
        market?: T;
        id?: T;
      };
  mainProducts?:
    | T
    | {
        product?: T;
        id?: T;
      };
  factoryLocation?: T;
  factorySize?: T;
  productionCapacity?: T;
  qualityCertifications?:
    | T
    | {
        certification?: T;
        id?: T;
      };
  tradeAssurance?: T;
  verifiedSupplier?: T;
  goldSupplier?: T;
  responseTime?: T;
  acceptSampleOrders?: T;
  acceptCustomOrders?: T;
  paymentTerms?:
    | T
    | {
        term?: T;
        id?: T;
      };
  businessRegistrationNumber?: T;
  taxId?: T;
  businessLicense?: T;
  companyWebsite?: T;
  socialMediaLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  companyVideo?: T;
  companyPhotos?: T;
  keyPersonnel?:
    | T
    | {
        name?: T;
        title?: T;
        email?: T;
        id?: T;
      };
  companyHistory?: T;
  factoryPhotos?: T;
  productionLinesCount?: T;
  qualityControlProcess?: T;
  rndCapability?: T;
  warehouseInformation?: T;
  shippingCapabilities?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  supplier?: T;
  moq?: T;
  bulkPricingTiers?:
    | T
    | {
        minQuantity?: T;
        price?: T;
        unit?: T;
        id?: T;
      };
  unitPrice?: T;
  sampleAvailable?: T;
  samplePrice?: T;
  customizationAvailable?: T;
  leadTime?: T;
  packagingOptions?:
    | T
    | {
        option?: T;
        id?: T;
      };
  shippingTerms?:
    | T
    | {
        term?: T;
        id?: T;
      };
  paymentTerms?:
    | T
    | {
        term?: T;
        id?: T;
      };
  productCertifications?:
    | T
    | {
        certification?: T;
        id?: T;
      };
  hsCode?: T;
  originCountry?: T;
  images?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rfqs_select".
 */
export interface RfqsSelect<T extends boolean = true> {
  buyer?: T;
  title?: T;
  description?: T;
  category?: T;
  products?:
    | T
    | {
        product?: T;
        quantity?: T;
        specifications?: T;
        id?: T;
      };
  quantity?: T;
  targetPrice?: T;
  deliveryDate?: T;
  deliveryLocation?: T;
  paymentTerms?:
    | T
    | {
        term?: T;
        id?: T;
      };
  status?: T;
  quotes?: T;
  selectedQuote?: T;
  expiryDate?: T;
  isPublic?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  rfq?: T;
  supplier?: T;
  products?:
    | T
    | {
        product?: T;
        quantity?: T;
        unitPrice?: T;
        id?: T;
      };
  totalPrice?: T;
  unitPrice?: T;
  quantity?: T;
  leadTime?: T;
  paymentTerms?:
    | T
    | {
        term?: T;
        id?: T;
      };
  shippingTerms?:
    | T
    | {
        term?: T;
        id?: T;
      };
  validityPeriod?: T;
  notes?: T;
  status?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  buyer?: T;
  supplier?: T;
  product?: T;
  subject?: T;
  message?: T;
  inquiryType?: T;
  status?: T;
  attachments?: T;
  lastRepliedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  inquiry?: T;
  sender?: T;
  receiver?: T;
  message?: T;
  attachments?: T;
  read?: T;
  readAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sample-requests_select".
 */
export interface SampleRequestsSelect<T extends boolean = true> {
  product?: T;
  buyer?: T;
  supplier?: T;
  quantity?: T;
  purpose?: T;
  shippingAddress?: T;
  status?: T;
  samplePrice?: T;
  paymentStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-catalogs_select".
 */
export interface ProductCatalogsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  supplier?: T;
  products?: T;
  coverImage?: T;
  category?: T;
  isPublic?: T;
  downloadUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  buyer?: T;
  supplier?: T;
  orderType?: T;
  products?:
    | T
    | {
        product?: T;
        quantity?: T;
        unitPrice?: T;
        totalPrice?: T;
        id?: T;
      };
  totalAmount?: T;
  paymentTerms?:
    | T
    | {
        term?: T;
        id?: T;
      };
  paymentSchedule?:
    | T
    | {
        amount?: T;
        dueDate?: T;
        status?: T;
        id?: T;
      };
  depositAmount?: T;
  depositPaid?: T;
  tradeAssurance?: T;
  escrowAmount?: T;
  shippingTerms?:
    | T
    | {
        term?: T;
        id?: T;
      };
  deliveryDate?: T;
  inspectionDate?: T;
  invoiceNumber?: T;
  poNumber?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}